include:
  - ci-templates/node.yml

image: node:16-alpine3.14

stages:
  - prepare
  - test
  - compile
  - doc
  - deploy

## install node dependencies
node:prepare:
  stage: prepare
  extends: .node-cache
  cache:
    policy: pull-push
  script:
    - npm ci --cache .npm --prefer-offline  --include=dev

common:lint:
  variables:
    CWD: packages/common
  extends: .node:lint
  stage: test
  needs: [node:prepare]

core:lint:
  variables:
    CWD: packages/core
  extends: .node:lint
  stage: test
  needs: [node:prepare]

common:unit:
  extends: .node:test:unit
  variables:
    CWD: packages/common
  stage: test
  needs: [node:prepare]

core:unit:
  extends: .node:test:unit
  variables:
    CWD: packages/core
  stage: test
  needs: [node:prepare]

common:build:
  extends: .node:build
  variables:
    CWD: packages/common
  stage: compile
  needs: [node:prepare]

core:build:
  extends: .node:build
  variables:
    CWD: packages/core
  stage: compile
  needs: [node:prepare]

common:docs:
  extends: .node:build
  variables:
    CWD: packages/common
    ARTIFACT_PATH: packages/common/dist/docs
  stage: doc
  needs: [node:prepare]
  script:
    - cd packages/common
    - npm run doc

core:docs:
  extends: .node:build
  variables:
    CWD: packages/core
    ARTIFACT_PATH: packages/core/dist/docs
  stage: doc
  needs: [node:prepare]
  script:
    - cd packages/core
    - npm run doc

# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/npm.gitlab-ci.yml

publish:gitlab:
  extends: .node:gitlab:publish
  stage: deploy
  needs:
    - core:build
    - common:build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+.*$/
      changes:
        - package.json
