image: node:13-alpine

stages:
  - prepare
  - build
  - test
  - publish

install:
  stage: prepare
  script:
    - yarn install
    - yarn add -DW puppeteer --only=dev

bundle:
  stage: build
  script:
    - apk add git && yarn build
  artifacts:
    paths:
      - dist/

lint:
  stage: build
  script:
    - yarn lint

test:
  stage: test
  script:
    - yarn test

#test:integration: ## will take up too much space when run over and over again.
#  stage: test
#  script:
#    - yarn test:integration
#  dependencies:
#    - bundle

test:size:
  stage: test
  script:
    - yarn size
  dependencies:
    - bundle

publish:
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/ && $CI_COMMIT_BRANCH == "master"'
    when: manual
  - when: never
  script: "echo 'publishing to NPM comming soon :)'"

cache:
  paths:
    - node_modules/

