image: node:14-alpine

stages:
  - prepare
  - build
  - test
  - publish

install:
  stage: prepare
  script:
    - yarn install

bundle:
  stage: build
  script:
    - apk add git && yarn build
  artifacts:
    paths:
      - dist/

lint:
  stage: build
  script:
    - yarn lint


docs:build:
  stage: build
  script:
    - yarn docs:build
    - cd docs/.vuepress/dist
    - git init
    - git add . -A
    - git commit -m"deploy doc"
    - git push -f git@github.com:NicolasThierion/aspectj.git master:gh-pages

test:
  stage: test
  script:
    - yarn test

#test:integration: ## will take up too much space when run over and over again.
#  stage: test
#  script:
#    - yarn test:integration
#  dependencies:
#    - bundle

test:size:
  stage: test
  script:
    - yarn size
  dependencies:
    - bundle


publish:
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/ && $CI_COMMIT_BRANCH == "master"'
    when: manual
  - when: never
  script: "echo 'publishing to NPM comming soon :)'; cd dist && yarn publish"

cache:
  paths:
    - node_modules/

