include:
  - ci-templates/node.yml
  - packages/core/.gitlab-ci.yml
  - packages/common/.gitlab-ci.yml
  - packages/memo/.gitlab-ci.yml
  - packages/persistence/.gitlab-ci.yml
  - packages/nestjs-client/.gitlab-ci.yml
  - packages/nestjs/.gitlab-ci.yml
  - packages/httyped-client/.gitlab-ci.yml

stages:
  - prepare
  - test
  - compile
  - doc
  - publish
  - release

## install node dependencies
node:prepare:
  stage: prepare
  extends: .node-cache
  cache:
    policy: pull-push
  script:
    - npm ci --cache .npm --prefer-offline  --include=dev

### DOCS

docs:
  extends: .node:build
  variables:
    ARTIFACT_PATH: packages/docs/dist/
  stage: doc
  needs:
    - node:prepare
  script:
    - npm run docs:build

  artifacts:
    expire_in: 20 min

docs:publish:
  image: alpine
  stage: release
  before_script:
    - apk add git openssh-client
    - mkdir -p ~/.ssh
    - cp $PAGES_SSH_PRIVATE_KEY ~/.ssh/id_rsa
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - chmod -R 600 ~/.ssh
    - git config --global user.email "nicolas.thierion+ci@outlook.com"
    - git config --global user.name "Gitlab CI"

  needs:
    - docs

  script:
    - cd packages/docs/
    - rm -rf .git .gitignore
    - git init --initial-branch=main
    - git add . dist .gitlab-ci.yml
    - git commit -m"deploy doc"
    - git push -f git@gitlab.com:aspectjs/aspectjs.gitlab.io.git main

  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true" && $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+.*$/

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "running release_job"
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_REF_NAME'
    description: '$CI_COMMIT_REF_NAME'
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^v\d+\.\d+\.\d+.*$/
      when: manual

.coverage:
  extends: .node:test:unit
  stage: test
  needs:
    - node:prepare
  script:
    - npm run test:coverage
