image: node:13-alpine

stages:
  - prepare
  - build
  - test
  - publish

install:
  stage: prepare
  script:
    - yarn install
    - yarn add -D puppeteer --only=dev

bundle:
  stage: build
  script:
    - apk add git && yarn build
  artifacts:
    paths:
      - dist/

lint:
  stage: build
  script:
    - yarn lint

test:
  stage: test
  script:
    - apk add git && yarn test

test:integration:
  image: buildkite/puppeteer:v1.15.0
  stage: test
  script:
    - apk add git && yarn test:integration
  dependencies:
    - bundle

test:size:
  image: buildkite/puppeteer:v1.15.0
  stage: test
  script:
    - apk add git && npm i size-limit && yarn size
  dependencies:
    - bundle

publish:
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/ && $CI_COMMIT_BRANCH == "master"'
    when: manual
  - when: never
  script: "echo 'publishing to NPM comming soon :)'"

cache:
  paths:
    - node_modules/

