image: node:13-alpine

stages:
  - prepare
  - build
  - test
  - publish

install:
  stage: prepare
  script:
    - npm install
    - npm install puppeteer --only=dev

bundle:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

lint:
  stage: build
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test

test:integration:
  image: buildkite/puppeteer:v1.15.0
  stage: test
  script:
    - npm run test:integration
  dependencies:
    - bundle

test:size:
  image: buildkite/puppeteer:v1.15.0
  stage: test
  script:
    - npm i size-limit && npm run size
  dependencies:
    - bundle

publish:
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/ && $CI_COMMIT_BRANCH == "master"'
    when: manual
  - when: never
  script: "echo 'publishing to NPM comming soon :)'"

cache:
  paths:
    - node_modules/

