image: node:13-alpine

workflow:
  rules:
   - if: '($CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/ && $CI_COMMIT_BRANCH == "master") || $CI_COMMIT_BRANCH == "ci"'
     when: always
   - when: never

stages:
  - prepare
  - build
  - test
  - publish

install:
  stage: prepare
  script:
    - npm install
    - npm install puppeteer --only=dev

bundle:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

lint:
  stage: build
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test

integration-test:
  image: buildkite/puppeteer:v1.15.0
  stage: test
  script:
    - npm run test:angular
  dependencies:
    - bundle

size-test:
  image: buildkite/puppeteer:v1.15.0
  stage: test
  script:
    - npm i size-limit && npm run size
  dependencies:
    - bundle

github:push:
  stage: publish
  image: alpine:3
  script:
    - export
    - apk add git openssh-client
    - mkdir ~/.ssh
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - cat $GITHUB_ID_RSA > ~/.ssh/id_rsa_github
    - chmod 600 ~/.ssh/id_rsa_github
    - echo -e 'Host github.com
      \n\tHostName github.com
      \n\tIdentityFile ~/.ssh/id_rsa_github
      \n\tUser git' >> ~/.ssh/config
    - git remote add github git@github.com:NicolasThierion/aspectjs-core.git
    - git push --tags github && git github master

cache:
  paths:
    - node_modules/
